name: UHCBase
version: '${project.version}'
main: me.butter.impl.UHCBase

commands:
    host:
        description: Commandes pour gérer la partie
        usage: /host <argument>
        aliases: h
    debug:
        description: Commandes de debug
        usage: /debug <argument>
        aliases: d