name: Ninjago
version: '${project.version}'
main: me.butter.ninjago.Ninjago

depend:
  - UHCBase

commands:
  n:
    description: Commande principale du mode de jeu
    usage: /n <argument>
    aliases: ni, ninjago, nj
