name: Impl
version: '${project.version}'
main: me.butter.impl.UHCImpl

commands:
    host:
        description: Définit l'host d'une partie
        usage: /host <argument>
        aliases: h
    rules:
        description: Permet de voir les informations sur la partie
        usage: /rules
    full:
        description: Permet de recuperer vos items
        usage: /full